### ISSUE TITLE
add opengraph image meta tag

### ISSUE THREAD

**Issue by jtemporal** [PizzaDeDados/pizzadedados#15]
We need a meta tag that links to the Pizza logo, so it will be displayed when the website is shared.

Here's the link for the image: `/assets/img/signo.png`

[and would be awesome if we could use the config path for the logo](https://github.com/PizzaDeDados/pizzadedados/blob/f4a1ca416f62dbf03c459a9b649d1e24dc709aae/_config.yml#L18) instead of hardcoding the path.

an example of said meta tag: `<meta name="og:image" content="http://ia.media-imdb.com/rock.jpg"/>`

**Comment by dharmad007** [comment]
can i work on this?
