### ISSUE TITLE
Atualizar seção "Pizzaiolas"

### ISSUE THREAD

**Issue by cecivieira** [PizzaDeDados/pizzadedados#26]
- [x] atualizar gênero do título
- [x] remover Gustavo
- [x] atualizar minibio
- [ ] trocar fotos

**Comment by fabiohcnobre** [comment]
Ola, o que seria esse genero do titulo?

**Comment by fabiohcnobre** [comment]
Criei um PR por gentileza poderia validar.

**Comment by cecivieira** [comment]
Novas descrições:

https://docs.google.com/document/d/1nzO_oWzPh3nx4xmYCYozSDS_iMpB2VsMpUfwk5rIdxY/edit
